/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package konversisuhu_202557201008;

/**
 *
 * @author Acer
 */
public class mainframe extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(mainframe.class.getName());

    /**
     * Creates new form mainframe
     */
    public mainframe() {
        initComponents();
        reset();
    }
        void reset(){
        tsuhuasal.setText(null);
        thasil.setText(null);
    }
        void konversi(){
        double suhuAsal = Double.parseDouble(tsuhuasal.getText());
        String satuanAsal =csuhuasal.getSelectedItem().toString();
        String satuanTujuan =csuhutujuan.getSelectedItem().toString();
        double hasil=0;
        if(satuanAsal=="Celcius"&&satuanTujuan=="Celcius"){
            hasil=suhuAsal;
        }else if(satuanAsal=="Celcius"&&satuanTujuan=="Reamur"){
            hasil = 4.0/5.0*suhuAsal;
        }else if(satuanAsal=="Celcius"&&satuanTujuan=="Kelvin"){
            hasil = suhuAsal+273.15;
        }else if(satuanAsal=="Celcius"&&satuanTujuan=="Fahrenheit"){
            hasil = (9.0/5.0*suhuAsal)+32;
        }else if(satuanAsal=="Reamur"&&satuanTujuan=="Reamur"){
            hasil = suhuAsal;
        }else if(satuanAsal=="Reamur"&&satuanTujuan=="Celcius"){
            hasil = 5.0/4.0*suhuAsal;
        }else if(satuanAsal=="Reamur"&&satuanTujuan=="Kelvin"){
            hasil = (5.0/4.0*suhuAsal)+273.15;
        }else if(satuanAsal=="Reamur"&&satuanTujuan=="Fahrenheit"){
            hasil = (9.0/4.0*suhuAsal)+32;
        }else if(satuanAsal=="Kelvin"&&satuanTujuan=="Kelvin"){
            hasil = suhuAsal;
        }else if(satuanAsal=="Kelvin"&&satuanTujuan=="Celcius"){
            hasil = suhuAsal-273.15;
        }else if(satuanAsal=="Kelvin"&&satuanTujuan=="Reamur"){
            hasil = 4.0/5.0*(suhuAsal-273.15);
        }else if(satuanAsal=="Kelvin"&&satuanTujuan=="Fahrenheit"){
            hasil = (9.0/5.0*(suhuAsal-273.15))+32;
        }else if(satuanAsal=="Fahrenheit"&&satuanTujuan=="Fahrenheit"){
            hasil = suhuAsal;
        }else if(satuanAsal=="Fahrenheit"&&satuanTujuan=="Celcius"){
            hasil = 5.0/9.0*(suhuAsal-32);
        }else if(satuanAsal=="Fahrenheit"&&satuanTujuan=="Reamur"){
            hasil = 4.0/9.0*(suhuAsal-32);
        }else if(satuanAsal=="Fahrenheit"&&satuanTujuan=="Kelvin"){
            hasil = (5.0/9.0*(suhuAsal-32))+273.15;
        }
        String derajat=satuanTujuan.substring(0,1); //mengambil indeks ke 0 , panjangnya 1 karakter
        thasil.setText(String.valueOf(hasil)+"\u00B0"+derajat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tsuhuasal = new javax.swing.JTextField();
        csuhuasal = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        csuhutujuan = new javax.swing.JComboBox<>();
        btnkonversi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        thasil = new javax.swing.JLabel();
        btnreset = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/konversisuhu_202557201008/icons8-temperature-64 SUHU.png"))); // NOI18N
        jLabel1.setText("KONVERSI SUHU");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("SATUAN ASAL"));

        tsuhuasal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tsuhuasalKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tsuhuasalKeyTyped(evt);
            }
        });

        csuhuasal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Kelvin", "Reamur", "Fahrenheit" }));
        csuhuasal.addActionListener(this::csuhuasalActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(csuhuasal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tsuhuasal))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(tsuhuasal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(csuhuasal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("KONVERSI KE"));

        csuhutujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celcius", "Kelvin", "Reamur", "Fahrenheit" }));
        csuhutujuan.addActionListener(this::csuhutujuanActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(csuhutujuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(csuhutujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnkonversi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/konversisuhu_202557201008/img/icons8-left-and-right-20.png"))); // NOI18N
        btnkonversi.setText("KONVERSI");
        btnkonversi.addActionListener(this::btnkonversiActionPerformed);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("HASIL"));

        thasil.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        thasil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thasil.setText("jLabel2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thasil, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/konversisuhu_202557201008/img/icons8-reset-20.png"))); // NOI18N
        btnreset.setText("RESET");
        btnreset.addActionListener(this::btnresetActionPerformed);

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/konversisuhu_202557201008/img/close new.png"))); // NOI18N
        btnclose.setText("CLOSE");
        btnclose.addActionListener(this::btncloseActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnkonversi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnreset)
                        .addGap(220, 220, 220)
                        .addComponent(btnclose))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnkonversi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnreset)
                    .addComponent(btnclose))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnresetActionPerformed

    private void tsuhuasalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsuhuasalKeyTyped
        // TODO add your handling code here:
        char huruf = evt.getKeyChar(); // mengambil dari keyboard 
        if(!Character.isDigit(huruf)&&huruf!='.'){
            evt.consume();
        }
    }//GEN-LAST:event_tsuhuasalKeyTyped

    private void btnkonversiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkonversiActionPerformed
        // TODO add your handling code here:
        konversi();
    }//GEN-LAST:event_btnkonversiActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btncloseActionPerformed

    private void tsuhuasalKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsuhuasalKeyReleased
        // TODO add your handling code here:
        konversi();
    }//GEN-LAST:event_tsuhuasalKeyReleased

    private void csuhuasalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csuhuasalActionPerformed
        // TODO add your handling code here:
        konversi();
    }//GEN-LAST:event_csuhuasalActionPerformed

    private void csuhutujuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csuhutujuanActionPerformed
        // TODO add your handling code here:
        konversi();
    }//GEN-LAST:event_csuhutujuanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new mainframe().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnkonversi;
    private javax.swing.JButton btnreset;
    private javax.swing.JComboBox<String> csuhuasal;
    private javax.swing.JComboBox<String> csuhutujuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel thasil;
    private javax.swing.JTextField tsuhuasal;
    // End of variables declaration//GEN-END:variables
}
